<?php
SYSTEM\autoload::registerFolder(dirname(__FILE__));
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/default_page');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/default_start');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/default_wir');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/default_medien');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/default_prototyp');
SYSTEM\autoload::registerFolder(dirname(__FILE__).'/default_help');