INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('main_startnext_status', 'deDE', 'Crowd-Funding auf <img src="./files/images/startnext_logo.png" alt="Startnext Logo" data-mce-src="files/images/startnext_logo.png"><br><strong>456</strong> Unterstützerinnen<br><strong>22.232€</strong> Spendensumme<br> <br><strong>11.907€</strong> fehlen noch<br> Noch <strong>9&nbsp;Tage</strong> - Mach mit!', 1, 1, '2017-11-17 17:29:13', '2017-11-17 17:29:13');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_ceta_og:description', 'deDE', 'CETA ist das Freihandelsabkommen mit Kanada. Stimme darüber ab, ob der Bundestag CETA zustimmen oder ablehnen soll.', 1, 1, '2017-11-17 16:52:06', '2017-11-17 16:52:06');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_ceta_og:image', 'deDE', 'https://www.democracy-deutschland.de/files/landing/ceta.jpg', 1, 1, '2017-11-17 17:09:32', '2017-11-17 17:09:32');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_ceta_og:title', 'deDE', 'App-stimmen über CETA - mit der DEMOCRACY App', 1, 1, '2017-11-17 17:03:03', '2017-11-17 17:03:03');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_ceta_og:url', 'deDE', 'https://www.democracy-deutschland.de/#!ceta', 1, 1, '2017-11-17 17:08:47', '2017-11-17 17:08:47');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_euro_og:description', 'deDE', 'Der Euro ist die verbindliche Währung der soganannten Euro-Zone innerhalb der Europäischen Union. Stimme darüber ab, ob der Bundestag aus dem Euro aussteigen oder verbleiben soll.', 1, 1, '2017-11-17 17:18:43', '2017-11-17 17:18:43');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_euro_og:image', 'deDE', 'https://www.democracy-deutschland.de/files/landing/euro.jpg', 1, 1, '2017-11-17 17:18:04', '2017-11-17 17:18:04');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_euro_og:title', 'deDE', 'Verbleib oder Ausstieg aus dem Euro - Stimme darüber ab mit der DEMOCRACY App', 1, 1, '2017-11-17 17:18:34', '2017-11-17 17:18:34');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_euro_og:url', 'deDE', 'https://www.democracy-deutschland.de/#!euro', 1, 1, '2017-11-17 17:18:22', '2017-11-17 17:18:22');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_gez_og:description', 'deDE', 'Der Rundfunkbeitrag&nbsp;ist in der&nbsp;Bundesrepublik Deutschland&nbsp;das gegenwärtige Modell zur&nbsp;Finanzierung&nbsp;der&nbsp;öffentlich-rechtlichen Rundfunkanstalten. Stimme darüber ab, wie die Mittel daraus verwendet werden sollen.', 1, 1, '2017-11-17 17:19:21', '2017-11-17 17:19:21');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_gez_og:image', 'deDE', 'https://www.democracy-deutschland.de/files/landing/gez.jpg', 1, 1, '2017-11-17 17:18:53', '2017-11-17 17:18:53');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_gez_og:title', 'deDE', 'Bei der Verwendung der GEZ Gebühr mitentscheiden - Stimme darüber ab mit der DEMOCRACY App', 1, 1, '2017-11-17 17:19:08', '2017-11-17 17:19:08');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_gez_og:url', 'deDE', 'https://www.democracy-deutschland.de/#!gez', 1, 1, '2017-11-17 17:19:01', '2017-11-17 17:19:01');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_staatstrojaner_og:description', 'deDE', 'Der Staatstrojaner ist einer der schwerwiegendsten Eingriffe in die Grundrechte der Bürger. Stimme darüber ab, ob der Bundestag den Staatstrojaner erlauben oder ablehnen soll.', 1, 1, '2017-11-17 17:19:56', '2017-11-17 17:19:56');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_staatstrojaner_og:image', 'deDE', 'https://www.democracy-deutschland.de/files/landing/staatstrojaner.jpg', 1, 1, '2017-11-17 17:19:35', '2017-11-17 17:19:35');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_staatstrojaner_og:title', 'deDE', 'App-stimmen über den Staatstrojaner - mit der DEMOCRACY App', 1, 1, '2017-11-17 17:19:49', '2017-11-17 17:19:49');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_staatstrojaner_og:url', 'deDE', 'https://www.democracy-deutschland.de/#!staatstrojaner', 1, 1, '2017-11-17 17:19:41', '2017-11-17 17:19:41');
REPLACE INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_start_author', 'deDE', 'Author', 1, 1, '2017-06-08 21:23:49', '2017-06-08 21:23:49');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_start_DC.Description', 'deDE', 'DEMOCRACY ist eine Initiative für mehr Basisdemokratie in Deutschland.', 1, 1, '2017-11-17 16:46:25', '2017-11-17 16:46:25');
REPLACE INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_start_description', 'deDE', 'Description', 1, 1, '2017-06-08 21:24:43', '2017-06-08 21:24:43');
REPLACE INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_start_keywords', 'deDE', 'Keywords', 1, 1, '2017-06-08 21:25:22', '2017-06-08 21:25:22');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_start_og:description', 'deDE', 'DEMOCRACY ist eine Initiative für mehr Basisdemokratie in Deutschland.', 1, 1, '2017-11-17 16:43:59', '2017-11-17 16:43:59');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_start_og:image', 'deDE', 'https://www.democracy-deutschland.de/files/images/forfb2.png', 1, 1, '2017-11-17 18:08:25', '2017-11-17 18:08:25');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('meta_start_og:url', 'deDE', 'https://www.democracy-deutschland.de/', 1, 1, '2017-11-17 18:08:54', '2017-11-17 18:08:54');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('title_ceta', 'deDE', 'CETA | DEMOCRACY Deutschland', 1, 1, '2017-11-18 20:36:06', '2017-11-18 20:36:06');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('title_euro', 'deDE', 'EURO AUSSTIEG | DEMOCRACY Deutschland', 1, 1, '2017-11-17 17:20:06', '2017-11-17 17:20:06');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('title_gez', 'deDE', 'GEZ VERWENDUNG | DEMOCRACY Deutschland', 1, 1, '2017-11-17 17:20:11', '2017-11-17 17:20:11');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('title_help', 'deDE', 'MITMACHEN | DEMOCRACY Deutschland', 1, 1, '2017-11-18 20:35:44', '2017-11-18 20:35:44');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('title_medien', 'deDE', 'MEDIEN | DEMOCRACY Deutschland', 1, 1, '2017-11-18 20:36:34', '2017-11-18 20:36:34');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('title_prototyp', 'deDE', 'PROTOTYP | DEMOCRACY Deutschland', 1, 1, '2017-11-18 20:36:47', '2017-11-18 20:36:47');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('title_staatstrojaner', 'deDE', 'STAATSTROJANER | DEMOCRACY Deutschland', 1, 1, '2017-11-17 17:20:18', '2017-11-17 17:20:18');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('title_start', 'deDE', 'DEMOCRACY Deutschland', 1, 1, '2017-11-17 16:42:22', '2017-11-17 16:42:22');
INSERT INTO `system_text` (`id`, `lang`, `text`, `author`, `author_edit`, `time_create`, `time_edit`) VALUES ('title_wir', 'deDE', 'WIR | DEMOCRACY Deutschland', 1, 1, '2017-11-18 20:37:02', '2017-11-18 20:37:02');

INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('main_startnext_status', 'democracy');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_ceta_og:description', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_ceta_og:description', 'meta_ceta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_ceta_og:image', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_ceta_og:image', 'meta_ceta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_ceta_og:title', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_ceta_og:title', 'meta_ceta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_ceta_og:url', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_ceta_og:url', 'meta_ceta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_euro_og:description', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_euro_og:description', 'meta_euro');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_euro_og:image', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_euro_og:image', 'meta_euro');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_euro_og:title', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_euro_og:title', 'meta_euro');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_euro_og:url', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_euro_og:url', 'meta_euro');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_gez_og:description', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_gez_og:description', 'meta_gez');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_gez_og:image', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_gez_og:image', 'meta_gez');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_gez_og:title', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_gez_og:title', 'meta_gez');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_gez_og:url', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_gez_og:url', 'meta_gez');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_staatstrojaner_og:description', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_staatstrojaner_og:description', 'meta_staatstrojaner');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_staatstrojaner_og:image', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_staatstrojaner_og:image', 'meta_staatstrojaner');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_staatstrojaner_og:title', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_staatstrojaner_og:title', 'meta_staatstrojaner');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_staatstrojaner_og:url', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_staatstrojaner_og:url', 'meta_staatstrojaner');
REPLACE INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_author', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_DC.Description', 'democracy');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_DC.Description', 'meta');
REPLACE INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_description', 'meta');
REPLACE INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_keywords', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_og:description', 'democracy');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_og:description', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_og:image', 'democracy');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_og:image', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_og:url', 'democracy');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('meta_start_og:url', 'meta');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_ceta', 'title');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_euro', 'title');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_gez', 'title');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_help', 'title');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_medien', 'title');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_prototyp', 'title');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_staatstrojaner', 'title');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_start', 'democracy');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_start', 'title');
INSERT INTO `system_text_tag` (`id`, `tag`) VALUES ('title_wir', 'title');