REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (10, 1, 'home', 'home', -1, 0, 0, '#content', './?page=home', 'init_home', 'default_home');
REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (11, 1, 'citizen', 'citizen', -1, 0, 0, '#content', './?page=citizen', 'init_citizen', 'default_citizen');
REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (12, 1, 'politicians', 'politicians', -1, 0, 0, '#content', './?page=politicians', 'init_politicians', 'default_politicians');
REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (13, 1, 'engeneering', 'engeneering', -1, 0, 0, '#content', './?page=engeneering', 'init_engeneering', 'default_engeneering');
REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (60, 1, 'donate', 'donate', -1, 0, 0, '#content', './?page=donate', 'init_donate', 'default_donate');

REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (45, 1, 'datenschutz', 'datenschutz', -1, 0, 0, '#content', './?page=datenschutz', 'init_datenschutz', 'default_datenschutz');
REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (40, 1, 'impressum', 'impressum', -1, 0, 0, '#content', './?page=impressum', 'init_impressum', 'default_impressum');
REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (30, 1, 'contact', 'contact', -1, 0, 0, '#content', './?page=contact', 'init_contact', 'default_contact');

REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (20, 1, 'press', 'press', -1, 0, 0, '#content', './?page=press', 'init_press', 'default_press');
REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (50, 1, 'faq', 'faq', -1, 0, 0, '#content', './?page=faq', 'init_faq', 'default_faq');

# REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (15, 1, 'wir', 'wir', -1, 0, 0, '#content', './?page=wir', 'init_wir', 'default_wir');
# REPLACE INTO `system_page` (`id`, `group`, `name`, `state`, `parent_id`, `login`, `type`, `div`, `url`, `func`, `php_class`) VALUES (25, 1, 'prototyp', 'prototyp', -1, 0, 0, '#content', './?page=prototyp', 'init_prototyp', 'default_prototyp');